# Generated by Django 3.0.3 on 2020-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200228_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.CharField(max_length=1)),
                ('some_another_text', models.CharField(max_length=1)),
            ],
        ),
    ]
